# Permalinks
permalink:           pretty

# Setup
title:               elektito
tagline:             'programming & stuff'
description:         'A blog for sharing my (mostly) programming related stuff.'
url:                 http://elektito.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mostafa Razavi
  url:               https://twitter.com/elektito
  email:             mostafa@sepent.com

# gems
gems:                [jekyll-paginate]
highlighter:         rouge