# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               elektito
tagline:             'my personal website'
description:         'This is my personal website and blog.'
url:                 http://elektito.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mostafa Razavi
  url:               https://twitter.com/elektito
  email:             mostafa@sepent.com

# Custom vars
version:             1.0.0

gems:                [jekyll-paginate]