# Permalinks
permalink:           pretty

# Setup
title:               elektito
tagline:             'my personal website'
description:         'This is my personal website and blog.'
url:                 http://elektito.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mostafa Razavi
  url:               https://twitter.com/elektito
  email:             mostafa@sepent.com

# gems
gems:                [jekyll-paginate, pygments.rb]
highlighter:         pygments